# Generated by Django 6.0.3 on 2026-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneryimage',
            name='latitude',
            field=models.FloatField(default=46.8182),
        ),
        migrations.AddField(
            model_name='sceneryimage',
            name='longitude',
            field=models.FloatField(default=8.2275),
        ),
    ]
